/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Coworker API
 * OpenAPI spec version: 0.0.1
 */

export interface ApiListMembersResponseMeta {
  page_count?: number;
  page_id?: number;
  page_size?: number;
  total_count?: number;
}
