/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * Coworker API
 * OpenAPI spec version: 0.0.1
 */
import type { ApiMemberResponse } from './apiMemberResponse'
import type { ApiListMembersResponseMeta } from './apiListMembersResponseMeta'

export interface ApiListMembersResponse {
  data?: ApiMemberResponse[]
  meta?: ApiListMembersResponseMeta
}
